### ISSUE TITLE
Timezone in README?

### ISSUE THREAD

**Issue by dmuth** [mandatoryprogrammer/NorthKoreaDNSLeak#2]
> On Sept 20, 2016 at approximately 10:00PM

This threw me off when I saw it, because it's currently 11:55 EDT (15:55 UTC) when I read this.  Maybe include a timezone? :-)

**Comment by mandatoryprogrammer** [comment]
Oomph! Good point :) isn't everyone from California? What do you mean _other_ timezones? My apologies, will fix!

**Comment by mandatoryprogrammer** [comment]
Updated README to reflect that I meant the Pacific Timezone!
