### ISSUE TITLE
README.MD seems to be from the future. 

### ISSUE THREAD

**Issue by miroatme** [mandatoryprogrammer/NorthKoreaDNSLeak#3]
On the README it says: On Sept 20, 2016 at approximately 10:00PM (PST), 
At time of writing that event will be in ~12 hours. Did this happen last night, the 19th?

**Comment by Fastjur** [comment]
Hmm very interesting indeed

**Comment by mandatoryprogrammer** [comment]
Wow, clearly I need to sleep more. It did happen last night _shakes head_

**Comment by mandatoryprogrammer** [comment]
Fixed, thanks guys!
