### ISSUE TITLE
Can I prevent this scan?

### ISSUE THREAD

**Issue by dnsconfused** [mandatoryprogrammer/NorthKoreaDNSLeak#4]
Other such DNS scanning services provide an opt-out.
Does this have such a "feature"

To be honest, other than "mildly interesting" what good is this continual scan and zone transfer request of every NS?

**Comment by mandatoryprogrammer** [comment]
Not sure why this was filed here, this is just an archive of North Korea's DNS data - the project you're talking about is here: https://github.com/mandatoryprogrammer/TLDR/ (you filed a separate issue there as well I see).

Closing this since it's a duplicate.

**Comment by totoCZ** [comment]
Chairman of the Workers' Party of Korea and supreme leader of the Democratic People's Republic of Korea, Kim Jong Un does not wish for his DNS servers to be scanned. Please remove. Thank.

The DNS servers were invented by the Supreme Leader in 1989 when he was 5 years old to serve the Korean population and not US imperialists interests.
