### ISSUE TITLE
Timezone in README is still wrong

### ISSUE THREAD

**Issue by ziggythehamster** [mandatoryprogrammer/NorthKoreaDNSLeak#5]
See #2 

September 19, 2016 was in Pacific _Daylight_ Time (PDT), not Pacific _Standard_ Time (PST) as indicated.

Yet another reason we need to kill daylight savings time.

**Comment by mandatoryprogrammer** [comment]
Wow, TIL, why does time have to be this complicated? Thanks for reporting, I've fixed it.
