### ISSUE TITLE
TL;DR vs TLDR?

### ISSUE THREAD

**Issue by nguyenmp** [mandatoryprogrammer/NorthKoreaDNSLeak#6]
I noticed this README references the TLD Records Archive as TL;DR but the projects README says TLDR with no semi-colon.  Was this intentional or was this a typo?

**Comment by chuushi** [comment]
> This was detected by the TL;DR Project

That is definitely a typo. TL;DR means "too long; didn't read", which doesn't make sense in the context.

**Comment by filwaitman** [comment]
... or it's a joke, dunno.

**Comment by mandatoryprogrammer** [comment]
Oops, was used to typing TL;DR, meant TLDR :) my bad.
